---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: debug-statements
      - id: trailing-whitespace
        exclude: ^tests/fixtures/
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.13
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        args: ["--exclude", "^tests/", "--ignore-missing-imports"]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: ./venv/bin/pytest tests
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
      - id: pytest-cov
        name: pytest-cov
        # The entry no longer needs a hardcoded path
        entry: pytest tests --cov=src --cov-report=xml --cov-fail-under=85
        language: python
        types: [python]
        pass_filenames: false
        always_run: true
        # pre-commit will install these dependencies in a managed environment
        additional_dependencies:
          - pytest
          - pytest-cov
          - pytest-mock
          - pandas
          - google-api-python-client
          - oauth2client
      - id: diff-coverage
        name: diff-coverage
        # The entry no longer needs a hardcoded path
        entry: diff-cover coverage.xml --fail-under=90 --compare-branch=master
        language: python
        types: [python]
        pass_filenames: false
        always_run: true
        # pre-commit installs diff-cover into the hook's environment
        additional_dependencies: [diff-cover]
  # - repo: https://github.com/PyCQA/pydocstyle
  #   rev: '6.3.0'
  #   hooks:
  #     - id: pydocstyle
  #       args:
  #         - --convention=google
